### ISSUE TITLE
Generate build pipeline YML to avoid unclear template usage

### ISSUE THREAD

**Issue by dagood** [microsoft/go#1073]
@gdams mentioned yml generation in a meeting (another team uses this general approach), and I really like it. So, I wrote it up as a pseudo-ADR, picking [MADR](https://github.com/adr/madr/blob/develop/template/adr-template.md) in particular, to try out that structure. (Although there are some "I" and clear opinions that I think I'd swap out if I were writing this to check in.)

## Context and Problem Statement

We use AzDO Pipeline templates a lot. To overcome reusability limitations in the pipeline yml language, we have templates that accept a "inner" template's filename as a parameter and calls the "inner" template with some additional parameters. This can be quite hard to unravel when reading straight through without already knowing the end goal.

This works ok once you're used to it, and sticking to template-time logic avoids a lot of other odd AzDO Pipelines evaluation behavior. However, adding additional layers of parameters-based-on-parameters is a significant mental tax for both implementers and readers, encouraging copy-paste and quick hacks over reuse, and resulting in unclear template name distinctions like `pool.yml` and `pool-core.yml` that only exist to create two template contexts.

This applies to microsoft/go for build/test/sign/publish, but also https://github.com/microsoft/go-infra for release automation pipelines. Those also use complicated pipeline yml patterns that would benefit from generation, perhaps even more than microsoft/go pipelines.

## Decision Drivers

* We want the pipelines to be maintainable.
* People new to the team should be able to follow how each pipeline works with minimal AzDO pipeline experience.

## Considered Options

* Leave it as it is. It's worked so far.
* Generate build pipeline YML using Go code.

## Decision Outcome

Generate build pipeline YML.

### Consequences

* Go is a much more featureful language than AzDO pipeline yml. We can more concisely and more clearly express the list of builders and the tweaks necessary for each platform/configuration.
* Someone who looks at our repo can easily read through the runnable pipeline yml and see the steps that are taken for a particular builder.
* We can have more confidence about how a change to core logic will affect (or not affect) every builder. This helps confidence with small fixes that are only intended to affect one platform.
  * It is technically possible to download AzDO-evaluated yml from an AzDO build, but that requires URL manipulation to get the data and the output is difficult to correlate to the actual templates (in my experience).
* We can include builder-specific details in yml comments to guide the reader, without compromising the maintainability of the yml.
  * With yml, you can e.g. document yml parameters, but when the same parameters are used in many files (simply for passthrough) it is a burden to document them in each place rather than having the reader look for the original source of the data themselves.
  * Large comments in the middle of a yml template make it harder to match up the indentation used for template `if`, `each`, and other nested structures, so scanning through the broad logic becomes more difficult.
* We can test the builder matrix and yml outputs themselves.
* I have some more complaints about pipeline yaml at https://github.com/microsoft/go-infra/blob/main/docs/pipeline-yml-style.md, and abstracting away from that language would likely let us avoid some of these quirks as well.
* In PR, reviewing Go code and evaluated yml at the same time can clarify *intent*, making it easier for the reviewer to spot problems and ignore non-problems.

However:

* When you discover a problem in a running pipeline, it may be more difficult to look at the generated yml and make a small fix, because the Go code that generated that code is what needs to change.
  * This can be mitigated by including references to Go code in the generated yml, but ultimately the fixer needs to understand to some degree how the Go code works.
* We would need to add CI to ensure the yml output always matches what the Go code would produce, to keep it in sync. For the same reason, devs submitting PRs that change the pipelines would also now need to run a tool to update the yml.
  * Ideally we would not check in any yml, and generate it inside the pipeline. As far as I know, this is not possible in AzDO pipelines. If it is possible, we will need to consider it separately, because it would also make it harder to spot pipeline yml quirks and increase the impact if our yml generator has a bug causing non-reproducible output.

### Confirmation

Some templates should still be used to make the resulting yml readable, and keep sharing functionality with .NET Arcade. However, a reasonable complexity metric would be: **no template accepts a template as a parameter**.

## More Information

Example template accepting a template, used to make parameters that depend on other parameters. Templates are from [eng/pipeline/stages](https://github.com/microsoft/go/tree/40b37427e190facf7833e1964d27f092ab3ddd01/eng/pipeline/stages). Our [pipeline entrypoint](https://github.com/microsoft/go/blob/40b37427e190facf7833e1964d27f092ab3ddd01/eng/pipeline/pr-pipeline.yml) calls a "matrix" template to set up the list of jobs:

```yml
stages:
  - template: stages/go-builder-matrix-stages.yml
    parameters:
      innerloop: true
```

The `go-builder-matrix-stages` template calls a "wrapper" template that will expand the objects in the `shorthandBuilders` array, telling the wrapper template what template to run internally once each object has additional properties added to it:

```yml
stages:
  - template: shorthand-builders-to-builders.yml
    parameters:
      jobsTemplate: builders-to-stages.yml
      jobsParameters:
        sign: ${{ parameters.sign }}
        createSourceArchive: ${{ parameters.createSourceArchive }}
        releaseVersion: ${{ parameters.releaseVersion }}
      shorthandBuilders:
        - ${{ if eq(parameters.innerloop, true) }}:
          - { os: linux, arch: amd64, config: buildandpack }
          - { os: linux, arch: amd64, config: devscript }
          - { os: linux, arch: amd64, config: test }
[...]
```

`shorthand-builders-to-builders` exists to create values that can be reused by the inner `jobsTemplate`. Without adding another layer of templates, you can't refer to one yml element's value from another one to build upon an existing value.

```yml
stages:
  - template: ${{ parameters.jobsTemplate }}
    parameters:
      ${{ insert }}: ${{ parameters.jobsParameters }}
      builders:
        - ${{ each builder in parameters.shorthandBuilders }}:
          - ${{ insert }}: ${{ builder }}
            # Use 'default' in place of null to define ID. This value just needs to be unique and
            # only contain "[A-z_]+".
            id: ${{ builder.os }}_${{ coalesce(builder.distro, 'default') }}_${{ coalesce(builder.hostArch, 'default') }}_${{ builder.arch }}_${{ builder.config }}_${{ coalesce(builder.experiment, 'default') }}_${{ coalesce(builder.fips, false) }}
            ${{ if not(builder.hostArch) }}:
              hostArch: ${{ builder.arch }}
[...]
```

In this case, `jobsTemplate` is `builders-to-stages`, which takes the expanded `builder` objects and passes them into the actual job template, adding more pipeline-specific parameters on top.

```yml
stages:
  - ${{ each builder in parameters.builders }}:
    - template: pool.yml
      parameters:
        inner:
          template: run-stage.yml
          parameters:
            builder: ${{ builder }}
            createSourceArchive: ${{ parameters.createSourceArchive }}
            releaseVersion: ${{ parameters.releaseVersion }}
[...]
```
