### ISSUE TITLE
CI break: MicroBuildToolset feed in nuget.config

### ISSUE THREAD

**Issue by dagood** [microsoft/go#207]
We need to remove this:

https://github.com/microsoft/go/blob/350e1804e578d36537933c76ea1ae3acefa5b2fe/eng/signing/NuGet.Config#L8

Arcade does this instead:

```yml
- ${{ if and(eq(parameters.runAsPublic, 'false'), ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
    - ${{ if eq(parameters.enableMicrobuild, 'true') }}:
      - task: MicroBuildSigningPlugin@3
        displayName: Install MicroBuild plugin
        inputs:
          signType: $(_SignType)
          zipSources: false
          feedSource: https://dnceng.pkgs.visualstudio.com/_packaging/MicroBuildToolset/nuget/v3/index.json
        env:
          TeamName: $(_TeamName)
        continueOnError: ${{ parameters.continueOnError }}
        condition: and(succeeded(), in(variables['_SignType'], 'real', 'test'), eq(variables['Agent.Os'], 'Windows_NT'))
```

We already use that task:

https://github.com/microsoft/go/blob/350e1804e578d36537933c76ea1ae3acefa5b2fe/eng/pipeline/jobs/sign-job.yml#L31-L34

Maybe we can just remove the NuGet.Config line.

See https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1631550925889?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1631550925889&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1631550925889
