### ISSUE TITLE
Make microsoft/go releases acquirable via `GoTool@0` Azure Pipelines task

### ISSUE THREAD

**Issue by dagood** [microsoft/go#483]
This task is easy to use and probably popular: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/go-tool?view=azure-devops. We use it ourselves, in go-infra.

I don't think our team should be in the business of creating an AzDO build task. I think we should try to get support added to the existing task for changing the base URL, at least: https://github.com/microsoft/azure-pipelines-tasks/blob/7abd0ed58d1951b8e3cca71c1401854b78bbc52c/Tasks/GoToolV0/gotool.ts#L97

**Comment by dagood** [comment]
* Filed https://github.com/microsoft/azure-pipelines-tasks/issues/16045

**Comment by dagood** [comment]
To catalog a few things... an implementation was attempted in:

* https://github.com/microsoft/azure-pipelines-tasks/pull/19000

We weren't directly involved in the attempt, and we [had to revert it at the time for a few reasons](https://github.com/microsoft/azure-pipelines-tasks/pull/19000#pullrequestreview-1638445480):

* https://github.com/microsoft/azure-pipelines-tasks/pull/19012

The Microsoft build of Go team hasn't had the resources since then to pick this back up and try to implement it in a way that would work for us.

Note that it's been a few years, so don't take my words back then as if they're set in stone. 😄

**Comment by dagood** [comment]
I was giving some pointers to @sb464f about this, and remembered this major issue with the GoTool@0 task:

* https://github.com/microsoft/azure-pipelines-tasks/issues/15825

It was closed due to being "stale" after no response from the repo maintainers, not because it was completed.

This behavior is misleading and not touched on in the documentation. It should be changed.

**Comment by dagood** [comment]
To write it out here:

The implementation of this should use the URLs specified at:
https://github.com/microsoft/go/blob/microsoft/main/eng/doc/Downloads.md

Specifically, this prefix: `https://aka.ms/golang/release/latest/`

Then, the Go version/platform can be appended, like `go1.24.6-1.linux-amd64.tar.gz`. We have URLs for floating versions (that is, "get latest of this major version") like `go1.24.linux-amd64.tar.gz`, and `GoTool@0` **should not** apply the `go1.24` -> `go1.24.0` version extension and should use these URLs directly to get the latest version of 1.24.

**Comment by dagood** [comment]
The implementation is complete in in this PR:

* https://github.com/microsoft/azure-pipelines-tasks/pull/21404

Now waiting for deployment.

**Comment by dagood** [comment]
Steps like this are expected to start working in version 0.265.0 of the task:

```yml
steps:
  - task: GoTool@0
    displayName: 'Install Go'
    inputs:
      version: '1.25'
      goDownloadUrl: 'https://aka.ms/golang/release/latest'
```

**Comment by mikaelweave** [comment]
@dagood This is working for me now. Thanks for the add, easier for us vs custom script.

```yaml
  - task: GoTool@0
    displayName: 'Install Go'
    inputs:
      version: ${{ parameters.goVersion }}
      goDownloadUrl: 'https://aka.ms/golang/release/latest'
```

<img width="3176" height="1348" alt="Image" src="https://github.com/user-attachments/assets/5b439f0d-436e-429f-b74f-a7061cf5dfb4" />
