### ISSUE TITLE
Make microsoft/go releases acquirable via setup-go GitHub Actions task

### ISSUE THREAD

**Issue by dagood** [microsoft/go#484]
The GitHub Actions Go setup task might need similar work as the AzDO task (https://github.com/microsoft/go/issues/483), but setup-go uses the https://golang.org/dl/?mode=json endpoint rather than direct URL construction so it might be significantly harder to support: https://github.com/actions/setup-go.

**Comment by gdams** [comment]
This is implemented now. We could still ship a JSON endpoint but for now users can do:

```yml
  - uses: actions/setup-go@v6
    with:
      go-version: '1.25'
      go-download-base-url: 'https://aka.ms/golang/release/latest'
```
