### ISSUE TITLE
Publish to branch name, not just the last `/` segment of branch name

### ISSUE THREAD

**Issue by dagood** [microsoft/go#60]
https://github.com/microsoft/go/blob/fb3157001f661ad20c396b6f8dd3e4e0bd27f6d4/microsoft/azure-pipelines.yml#L39

`$(Build.SourceBranchName)` is misleading: with the ref name `refs/heads/microsoft/main`, it gives only the last segment, `main`. (This is [documented AzDO behavior](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables).) I would call the branch's name `microsoft/main`.

This can cause overlap if someone runs a dev build of a branch called e.g. `dev/dagood/do-foo/main`. I sometimes would do this if I planned to develop the same change for multiple branches. (`dev/dagood/do-foo/release-branch.go1.16`) The `main` overlap would mean that my build output shows up indistinguishable from a `microsoft/main` build, if you only look at blob storage.

We handled this [in .NET (runtime/setup)](https://github.com/dotnet/windowsdesktop/blob/ee77657a20ff4dd1749f64c283fa451b4f9b6b03/eng/jobs/run-publish-project.yml#L118-L128) with a step like this:

```yml
  - powershell: |
      $prefix = "refs/heads/"
      $branch = "$(Build.SourceBranch)"
      $branchName = $branch
      if ($branchName.StartsWith($prefix))
      {
        $branchName = $branchName.Substring($prefix.Length)
      }
      Write-Host "For Build.SourceBranch $branch, FullBranchName is $branchName"
      Write-Host "##vso[task.setvariable variable=FullBranchName;]$branchName"
    displayName: Find true SourceBranchName
```

Looks like Roslyn uses a [oneliner](https://github.com/dotnet/roslyn/blob/f9c1e51f9450326a654a7987e2048f847f24e3a8/azure-pipelines-official.yml#L75-L77) that assumes it'll always have a `refs/heads/` prefix:

```yml
    - powershell: Write-Host "##vso[task.setvariable variable=SourceBranchName]$('$(Build.SourceBranch)'.Substring('refs/heads/'.Length))"
      displayName: Setting SourceBranchName variable
      condition: succeeded()
```
